apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice
  labels:
    app: python-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
      - name: python-microservice
        image: python-microservice:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "1.0.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"