apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-microservice-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'file:///tmp/python-microservice'  # We'll use local path for demo
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: python-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true